### ISSUE TITLE
Other block parsers?

### ISSUE THREAD

**Issue by ssivakorn** [6457/whois#3]
Hi, thank you for sharing the code. Is there any chance that we could have the parsers for other WHOIS record blocks too (e.g., registrat, domain) like shown in the paper at IMC 2015? Currently only registrant block is available (RantParser.java). Particularly we are interested in testing your Date and Domain block parsers. Thank you! :)

**Comment by grommitz** [comment]
Hi @ssivakorn , did you manage to extract anything with this library? Whenever I run it I get the message "Empty data!" even though I pass in a full whois record.
BTW on my fork (https://github.com/grommitz/whois) I have converted to a maven build & added a junit test for playing with it, if that's of any use.
Martin

**Comment by 6457** [comment]
Hi @ssivakorn , most other information, such as registrar, domain, status and so on, can be directly extracted from thin whois, which can be easily parsed using templates. A thin parser is also included in the code. In our project, we were mostly concerned with registrant information, which cannot be extracted elsewhere. Other blocks, such as admin, tech can also be retrieved using the same approach if needed, but needs labeled data.

**Comment by 6457** [comment]
Hi @grommitz , thank you for your interest in the project and creating unit test. I've looked into your examples, however, it seems that you only have thin whois data, which can be extracted using our template thin parser. I've investigated this issue and found that the whois query command has changed over the past year to only provide thin data. It used to return both thin and thick. Probably you need to find ways to obtain thick whois before you can parse any registrant information.
